"""index box_session_event type session_id

Revision ID: 1e51e5a9597e
Revises: abececed02c7
Create Date: 2026-07-15 10:12:04.044805

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1e51e5a9597e"
down_revision: Union[str, Sequence[str], None] = "abececed02c7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_box_session_event_type_session_id",
        "box_session_event",
        ["type", "session_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_box_session_event_type_session_id", table_name="box_session_event"
    )
    # ### end Alembic commands ###
