"""baseline schema

Revision ID: abececed02c7
Revises: 
Create Date: 2026-07-14 08:20:09.611987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'abececed02c7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('box',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('tag', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mining_location',
    sa.Column('venue_name', sa.String(), nullable=False),
    sa.Column('gem_type', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mining_location_venue_name'), 'mining_location', ['venue_name'], unique=True)
    op.create_table('player',
    sa.Column('tag', sa.String(), nullable=False),
    sa.Column('origin_id', sa.Uuid(), nullable=False),
    sa.Column('pin_hash', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['origin_id'], ['box.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('box_session',
    sa.Column('box_id', sa.Uuid(), nullable=False),
    sa.Column('host_player_id', sa.Uuid(), nullable=True),
    sa.Column('player_ids', sqlite.JSON(), nullable=False),
    sa.Column('game_tag', sa.String(), nullable=False),
    sa.Column('session_type', sa.String(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['box_id'], ['box.id'], ),
    sa.ForeignKeyConstraint(['host_player_id'], ['player.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stripe_payment_intent',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('stripe_session_id', sa.String(), nullable=False),
    sa.Column('stripe_payment_intent_id', sa.String(), nullable=False),
    sa.Column('player_id', sa.Uuid(), nullable=False),
    sa.Column('box_id', sa.Uuid(), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('credits_purchased', sa.Integer(), nullable=False),
    sa.Column('bonus_credits', sa.Integer(), nullable=False),
    sa.Column('selected_price_id', sa.String(), nullable=True),
    sa.Column('payment_method', sa.String(), nullable=False),
    sa.Column('payment_method_type', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('credit_event_id', sa.Uuid(), nullable=True),
    sa.Column('credited_to_session_id', sa.Uuid(), nullable=True),
    sa.Column('credited_at', sa.DateTime(), nullable=True),
    sa.Column('payment_metadata', sqlite.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['box_id'], ['box.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_stripe_payment_intent_box_id', 'stripe_payment_intent', ['box_id'], unique=False)
    op.create_index('ix_stripe_payment_intent_player_id', 'stripe_payment_intent', ['player_id'], unique=False)
    op.create_index('ix_stripe_payment_intent_status', 'stripe_payment_intent', ['status'], unique=False)
    op.create_index(op.f('ix_stripe_payment_intent_stripe_payment_intent_id'), 'stripe_payment_intent', ['stripe_payment_intent_id'], unique=True)
    op.create_index(op.f('ix_stripe_payment_intent_stripe_session_id'), 'stripe_payment_intent', ['stripe_session_id'], unique=True)
    op.create_table('box_session_event',
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('payload', sqlite.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['box_session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stripe_webhook_event',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('stripe_event_id', sa.String(), nullable=False),
    sa.Column('stripe_event_type', sa.String(), nullable=False),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('processing_error', sa.String(), nullable=True),
    sa.Column('payment_intent_id', sa.Uuid(), nullable=True),
    sa.Column('event_data', sqlite.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['payment_intent_id'], ['stripe_payment_intent.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stripe_webhook_event_stripe_event_id'), 'stripe_webhook_event', ['stripe_event_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stripe_webhook_event_stripe_event_id'), table_name='stripe_webhook_event')
    op.drop_table('stripe_webhook_event')
    op.drop_table('box_session_event')
    op.drop_index(op.f('ix_stripe_payment_intent_stripe_session_id'), table_name='stripe_payment_intent')
    op.drop_index(op.f('ix_stripe_payment_intent_stripe_payment_intent_id'), table_name='stripe_payment_intent')
    op.drop_index('ix_stripe_payment_intent_status', table_name='stripe_payment_intent')
    op.drop_index('ix_stripe_payment_intent_player_id', table_name='stripe_payment_intent')
    op.drop_index('ix_stripe_payment_intent_box_id', table_name='stripe_payment_intent')
    op.drop_table('stripe_payment_intent')
    op.drop_table('box_session')
    op.drop_table('player')
    op.drop_index(op.f('ix_mining_location_venue_name'), table_name='mining_location')
    op.drop_table('mining_location')
    op.drop_table('box')
    # ### end Alembic commands ###
